development:
  github_webhook_secret_token: <%= ENV["GITHUB_WEBHOOK_SECRET_TOKEN"] %>

test:
  github_webhook_secret_token: <%= ENV["GITHUB_WEBHOOK_SECRET_TOKEN"] %> 

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  github_webhook_secret_token: <%= ENV["GITHUB_WEBHOOK_SECRET_TOKEN"] %>
